server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters: TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/car/**
        - id: motorbike-service
          uri: lb://motorbike-service
          predicates:
            - Path=/motorbike/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/test-gateway-01
            authorization-uri: http://localhost:8180/auth/realms/test-gateway-01/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8180/auth/realms/test-gateway-01/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          test-scope:
            provider: keycloak
            client-id: test-scope
            client-secret: b199b840-0903-4427-913e-daed697b005a
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/test-scope"