server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: registry-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
          - id: car-service
              uri: lb://car-service
              predicates:
                - Path=/car/**
          - id: car-service
              uri: lb://motorbike-service
              predicates:
                - Path=/motorbike/**
